site_name: Notes
site_url: https://dinhhuy258.github.io/notes/
repo_url: https://github.com/dinhhuy258/notes
site_author: Huy Duong
site_description: Huy Duong's notes
copyright: Copyright &copy; 2021 - 2021 Huy Duong

# Configuration
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.top
    - toc.integrate
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github

extra:
  disqus: huyduong-notes

# Extensions
markdown_extensions:
  - pymdownx.highlight:
      linenums: true
  - pymdownx.superfences
  - pymdownx.inlinehilite

# Page tree
nav:
  - Home: index.md
  - Algorithms:
    - Binary search: algorithms/binary_search.md
    - KMP: algorithms/kmp.md
    - Bucket sort: algorithms/bucket_sort.md
    - Huffman coding: algorithms/huffman_coding.md
    - Union find: algorithms/union_find.md
    - Monotonic stack: algorithms/monotonic_stack.md
    - Minimum spanning tree: algorithms/minimum_spanning_tree.md
    - Shortest Path Algorithms: algorithms/shortest_path_algorithms.md
    - Articulation Points and Bridges: algorithms/articulation_points_and_bridges.md
    - Topological Sort: algorithms/topological_sort.md
    - Rolling hash: algorithms/rolling_hash.md
    - Bloom filter: algorithms/bloom_filter.md
  - Distributed System:
    - Distributed System: distributed-system/distributed_system.md
    - Cohesion and coupling: distributed-system/cohesion_and_coupling.md
    - Microservice communication: distributed-system/microservice_communication.md
  - Web:
    - HTTP: web/http.md
    - Networking:
      - TCP: web/networking/tcp.md
    - Security:
      - JWT: web/security/jwt.md
      - OAuth2: web/security/oauth2.md
      - CORS: web/security/cors.md
    - Database:
      - SQL cheat sheet: web/database/sql_cheat_sheet.md
      - MySQL: web/database/mysql.md
      - Transactions: web/database/transactions.md
      - NoSQL: web/database/nosql.md
      - Cassandra: web/database/cassandra.md
    - WebRTC:
      - WebRTC: web/webrtc/webrtc.md
      - Signaling: web/webrtc/signaling.md
      - Connecting: web/webrtc/connecting.md
      - Media communication: web/webrtc/media_communication.md
      - Example: web/webrtc/example.md
  - Programming:
    - Golang:
      - Array and slice: programming/golang/array_and_slice.md
      - Goroutine: programming/golang/goroutine.md
      - Context: programming/golang/context.md
    - Git:
      - Git commands: programming/git/git_commands.md
    - Kotlin:
      - Coroutine:
        - Coroutine basics: programming/kotlin/coroutine/basics.md
        - Coroutine context and dispatchers: programming/kotlin/coroutine/context_and_dispatchers.md
  - Devops:
    - Kubernetes:
      - Pods: devops/kubernetes/pods.md
      - Controllers: devops/kubernetes/controllers.md
      - Service: devops/kubernetes/service.md
      - Ingress: devops/kubernetes/ingress.md
      - Volumes: devops/kubernetes/volumes.md
      - ConfigMaps: devops/kubernetes/config_maps.md
