site_name: Notes
site_url: https://dinhhuy258.github.io/notes/
repo_url: https://github.com/dinhhuy258/notes
site_author: Huy Duong
site_description: Huy Duong's notes
copyright: Copyright &copy; 2021 - 2021 Huy Duong

# Configuration
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.top
    - toc.integrate
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github

extra:
  disqus: huyduong-notes

# Extensions
markdown_extensions:
  - pymdownx.highlight:
      linenums: true
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

# Page tree
nav:
  - Home: index.md
  - Algorithms:
    - Binary search: algorithms/binary_search.md
    - KMP: algorithms/kmp.md
    - Bucket sort: algorithms/bucket_sort.md
    - Huffman coding: algorithms/huffman_coding.md
    - Union find: algorithms/union_find.md
    - Monotonic stack: algorithms/monotonic_stack.md
    - Minimum spanning tree: algorithms/minimum_spanning_tree.md
    - Shortest Path Algorithms: algorithms/shortest_path_algorithms.md
    - Articulation Points and Bridges: algorithms/articulation_points_and_bridges.md
    - Topological Sort: algorithms/topological_sort.md
    - String Hashing: algorithms/string_hashing.md
    - Bloom filter: algorithms/bloom_filter.md
    - Binary indexed tree: algorithms/binary_indexed_tree.md
    - Segment tree: algorithms/segment_tree.md
    - Submask Enumeration : algorithms/submask_enumeration.md
    - Ternary Search: algorithms/ternary_search.md
  - Distributed System:
    - HTTP: distributed-system/http.md
    - Causal Consistency: distributed-system/causal_consistency.md
    - Networking:
      - TCP: distributed-system/networking/tcp.md
      - Understanding socket and port in TCP: distributed-system/networking/understanding_socket_and_port_in_tcp.md
      - SSH Tunnel: distributed-system/networking/ssh_tunnel.md
    - Security:
      - Web Security: distributed-system/security/web_security.md
      - JWT: distributed-system/security/jwt.md
      - OAuth2: distributed-system/security/oauth2.md
      - OpenId Connect: distributed-system/security/openid_connect.md
      - CORS: distributed-system/security/cors.md
    - WebRTC:
      - WebRTC: distributed-system/webrtc/webrtc.md
      - Signaling: distributed-system/webrtc/signaling.md
      - Connecting: distributed-system/webrtc/connecting.md
      - Media communication: distributed-system/webrtc/media_communication.md
      - Example: distributed-system/webrtc/example.md
    - ZooKeeper:
      - Fundamentals: distributed-system/zookeeper/fundamentals.md
      - Workflow: distributed-system/zookeeper/workflow.md
      - Leader Election: distributed-system/zookeeper/leader_election.md
    - Kafka:
      - Kafka Architecture: distributed-system/kafka/kafka_architecture.md
      - Installation: distributed-system/kafka/installation.md
      - Producer: distributed-system/kafka/producer.md
      - Consumer: distributed-system/kafka/consumer.md
      - Reliable Data Delivery: distributed-system/kafka/reliable_data_delivery.md
      - Exactly-Once Semantics: distributed-system/kafka/exactly_once_semantics.md
      - Kafka Connect: distributed-system/kafka/kafka_connect.md
    - Distributed System: distributed-system/distributed_system.md
    - Cohesion and coupling: distributed-system/cohesion_and_coupling.md
    - Microservice communication: distributed-system/microservice_communication.md
    - Service discovery: distributed-system/service_discovery.md
    - API Gateway: distributed-system/api_gateway.md
    - Service Mesh: distributed-system/service_mesh.md
  - Database:
    - PostgreSQL:
      - How Postgres Stores Rows: database/postgres/how_postgres_stores_rows.md
      - Concurrency Control: database/postgres/concurrency_control.md
      - Vacuum Processing: database/postgres/vacuum_processing.md
      - Heap Only Tuple and Index-Only Scans: database/postgres/heap_only_tuple_and_index_only_scans.md
      - Buffer Manager: database/postgres/buffer_manager.md
      - Write Ahead Logging: database/postgres/write_ahead_logging.md
      - Streaming Replication: database/postgres/streaming_replication.md
      - Query Processing: database/postgres/query_processing.md
      - Bitmap Index Scan: database/postgres/bitmap_index_scan.md
      - Brin Index: database/postgres/brin_index.md
    - DynamoDB:
      - Data Model: database/dynamodb/data_model.md
      - Read & Write Data: database/dynamodb/read_write_data.md
      - Secondary Index: database/dynamodb/secondary_index.md
    - SQL cheat sheet: database/sql_cheat_sheet.md
    - MySQL: database/mysql.md
    - Transactions: database/transactions.md
    - NoSQL: database/nosql.md
    - Cassandra: database/cassandra.md
    - LSM Tree: database/lsm_tree.md
    - Btree vs B+tree: database/btree_vs_b_plus_tree.md
    - Offset is bad: database/offset_is_bad.md
  - Programming:
    - Golang:
      - Array and slice: programming/golang/array_and_slice.md
      - Goroutine: programming/golang/goroutine.md
      - Context: programming/golang/context.md
    - Git:
      - Git commands: programming/git/git_commands.md
      - Find bug with Git Bisect command: programming/git/git_bisect.md
    - Kotlin:
      - Coroutine:
        - Coroutine basics: programming/kotlin/coroutine/basics.md
        - Coroutine context and dispatchers: programming/kotlin/coroutine/context_and_dispatchers.md
    - Tips:
      - Debugging Laravel Sail with XDebug: programming/tips/debugging-laravel-sail-with-xdebug.md
  - Devops:
    - AWS:
      - IAM: devops/aws/iam.md
      - EC2: devops/aws/ec2.md
      - Elastic Load Balancing and Auto Scaling groups: devops/aws/elb_asg.md
      - RDS: devops/aws/rds.md
      - Route 53: devops/aws/route_53.md
      - S3: devops/aws/s3.md
      - CloudFront: devops/aws/cloud_front.md 
      - ECS: devops/aws/ecs.md
      - SQS/SNS: devops/aws/sqs_sns.md
      - VPC: devops/aws/vpc.md
    - Docker:
      - Docker Overview: devops/docker/docker.md
      - Docker Images: devops/docker/docker_images.md
      - Docker Storage: devops/docker/docker_storage.md
      - Docker Network: devops/docker/docker_network.md
      - Docker Cheat Sheet: devops/docker/docker_cheat_sheet.md
    - Kubernetes:
      - Cluster Architecture: devops/kubernetes/cluster_architecture.md
      - Pods: devops/kubernetes/pods.md
      - Controllers: devops/kubernetes/controllers.md
      - Service: devops/kubernetes/service.md
      - Ingress: devops/kubernetes/ingress.md
      - Volumes: devops/kubernetes/volumes.md
      - ConfigMaps and Secrets: devops/kubernetes/config_maps_and_secrets.md
    - Terraform:
      - Terraform: devops/terraform/terraform.md
      - Input Variables: devops/terraform/input_variables.md
      - Locals: devops/terraform/locals.md
      - Data Sources: devops/terraform/data_sources.md
      - Resources: devops/terraform/resources.md
      - Files: devops/terraform/files.md
      - Terragrunt: devops/terraform/terragrunt.md
  - Blogs: blogs/index.md
